- kind: SpannerDatabase
  name: CommentDatabase
  tables:
    - kind: Table
      name: Comment
      columns:
        - name: commentId
          type: string
        - name: seasonId
          type: string
          nullable: true
        - name: episodeId
          type: string
          nullable: true
        - name: authorId
          type: string
          nullable: true
        - name: content
          type: string
          nullable: true
        - name: pinnedVideoTimeMs
          type: float64
          nullable: true
        - name: postedTimeMs
          type: float64
          nullable: true
      primaryKeys:
        - commentId
      indexes:
        - name: CommentsInEpisode
          columns:
            - seasonId
            - episodeId
            - pinnedVideoTimeMs
        - name: CommentsByPostedTime
          columns:
            - authorId
            - name: postedTimeMs
              desc: true
      insert: InsertComment
      delete: DeleteComment
      get: GetComment
  selects:
    - name: ListCommentsOfEpisode
      from: Comment
      where:
        op: AND
        exprs:
          - op: =
            lColumn: seasonId
          - op: =
            lColumn: episodeId
          - op: ">="
            lColumn: pinnedVideoTimeMs
          - op: "<"
            lColumn: pinnedVideoTimeMs
      orderBy:
        - pinnedVideoTimeMs
      get:
        - all: true
    - name: ListCommentsByPostedTime
      from: Comment
      where:
        op: AND
        exprs:
          - op: =
            lColumn: authorId
          - op: <
            lColumn: postedTimeMs
      orderBy:
        - column: postedTimeMs
          desc: true
      withLimit: true
      get:
        - all: true
  outputDdl: ./db/ddl
  outputSql: ./db/sql